### testing unknown endpoint
GET http://localhost:4000/api/nonexistent

### testing router
GET http://localhost:4000/api/quotes/receive

### GET all
GET http://localhost:4000/api/quotes

### GET by ID
GET http://localhost:4000/api/quotes/65faa1d0044a892e9fba88c6

### Create
POST http://localhost:4000/api/quotes
Content-Type: application/json

{
  "quote": "Coding in Color",
  "author": "- T.A.Y",
  "category": "Coders"
}

### UPDATE by ID
PUT http://localhost:4000/api/quotes/65fb033df93e1f63b67f8142
Content-Type: application/json

{
  "quote": "Testing PUT request on PORT 4000",
  "author": "Updated author",
  "category": "Updated category"
}

### DELETE by ID
DELETE http://localhost:4000/api/quotes/65fb033df93e1f63b67f8142