### testing quoteListRouter
GET http://localhost:4000/api/quoteLists/receive

### GET all
GET http://localhost:4000/api/quoteLists

### GET by ID
GET http://localhost:4000/api/quoteLists/660513811d1853aa27f87b96

### Create
POST http://localhost:4000/api/quoteLists/660510e71d1853aa27f87b8d
Content-Type: application/json

{
  "name": " General Quotes List"
}


### UPDATE by ID
PUT http://localhost:4000/api/quoteLists/65fcbfa39641d7553258a88b
Content-Type: application/json

{
  "name": " Quotes list"
}

### DELETE by ID
DELETE http://localhost:4000/api/quoteLists/6606b87b95506159236634cd
Content-Type: application/json

{
  "userId": "660510e71d1853aa27f87b8d"
}
