### testing quoteListRouter
GET http://localhost:4000/api/quoteLists/receive

### GET all
GET http://localhost:4000/api/quoteLists

### GET by ID
GET http://localhost:4000/api/quoteLists/

### Create
POST http://localhost:4000/api/quoteLists/65fad7105fa8d1b66af850b4
Content-Type: application/json

{
  "name": " Test Quotes List"
}


### UPDATE by ID
PUT http://localhost:4000/api/quoteLists/65fcbfa39641d7553258a88b
Content-Type: application/json

{
  "name": " Quotes list"
}

### DELETE by ID
DELETE http://localhost:4000/api/quoteLists/65fcf10de4b931b51a942a9a
Content-Type: application/json

{
  "userId": "65faea3fe81c81504b1abd82"
}
