### testing unknown endpoint
GET http://localhost:4000/api/nonexistent

### testing router
GET http://localhost:4000/api/quotes/receive

### GET all
GET http://localhost:4000/api/quotes

### GET by ID
GET http://localhost:4000/api/quotes/

### Create
POST http://localhost:4000/api/quotes/65fcbfa39641d7553258a88b
Content-Type: application/json

{
  "quote": "Coding in Color",
  "author": "- T.A.Y",
  "category": "Coders"
}

### UPDATE by ID
PUT http://localhost:4000/api/quotes/65fd41b4b63a4a75dbc2a2f2
Content-Type: application/json

{
  "quote": "Testing PUT request on PORT 4000",
  "author": "Updated author",
  "category": "Updated category"
}

### DELETE by ID
DELETE http://localhost:4000/api/quotes/65fd4f1886fd478c0dc09382