### testing userRouter
GET http://localhost:4000/api/users/receive

### GET all
GET http://localhost:4000/api/users

### GET by ID
GET http://localhost:4000/api/users/66037e2c02ce9f0610e077fe

### Create
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "username": "Dummy",
    "password": "xYz"
}

### UPDATE by ID
PUT http://localhost:4000/api/users/
Content-Type: application/json

{
    "username": "updated Username",
    "password": "updated Password"
}

### DELETE by ID
DELETE http://localhost:4000/api/users/660510e71d1853aa27f87b8d